Layout/EmptyLinesAroundBlockBody:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/ClassAndModuleChildren:
  Exclude:
    - 'test/test_helper.rb'

Style/MixinUsage:
  Exclude:
    - 'bin/setup'
    - 'bin/update'

Style/StderrPuts:
  Exclude:
    - 'bin/yarn'

Style/SymbolArray:
  EnforcedStyle: brackets

Metrics/LineLength:
  Max: 120
