version: '3'
volumes:
  postgres-data:
  app-bundle:
services:
  postgres:
    image: postgres:9.6.9-alpine
    environment:
      POSTGRES_USER: 'web_analytics'
      POSTGRES_PASSWORD: 't0p53kr1t'
      POSTGRES_DB: 'web_analytics_development'
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
  app:
    build: .
    command: '/web_analytics/bin/entrypoint'
    environment:
      # Using just `web_analytics` for the db name so we can suffix the correct name in `database.yml`
      DATABASE_URL: 'postgres://web_analytics:t0p53kr1t@postgres:5432/web_analytics?encoding=utf8&pool=5&timeout=5000'
    volumes:
      - .:/web_analytics:cached
      - app-bundle:/usr/local/bundle
    ports:
      - 3000:3000
    depends_on:
      - postgres
    stdin_open: true
    tty: true
